services:
  vue-fastapi-admin:
    image: vue-fastapi-admin:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_TAG=${NODE_TAG}
        - PYTHON_TAG=${PYTHON_TAG}
    container_name: vue-fastapi-admin
    ports:
      - "8080:80"
    restart: always
